# -*- coding: utf-8 -*-
"""fake news.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1gSNEvyrQRZoVl2PELUgDXhFGkcejNQoM
"""

from transformers import pipeline
import numpy as np

classifier = pipeline(
    "text-classification",
    model="jy46604790/Fake-News-Bert-Detect",
    return_all_scores=True
)

news_samples = [
    "The government has announced a new policy to improve education standards.",
    "NASA confirms the earth will go dark for six days next month.",
    "Scientists discover a new species of bird in the Amazon rainforest.",
    "Drinking hot water cures cancer instantly, doctors say."
]

results = classifier(news_samples)

for news, prediction in zip(news_samples, results):
    print("News:", news)

    for label_score in prediction:
        print(f"Label: {label_score['label']}, Confidence: {label_score['score']:.2f}")

    print("-" * 60)

