# -*- coding: utf-8 -*-
"""sentiment analysis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1PesTjJga3Jdf6LGwzFlOE3l2Gdyk2Njw
"""

!pip install transformers torch numpy

from transformers import pipeline
import numpy as np
sentiment_pipeline = pipeline(
    "sentiment-analysis",
    model="distilbert-base-uncased-finetuned-sst-2-english"
)
texts = [
    "I absolutely love this product!",
    "The service was okay, not great",
    "This is the worst experience I ever had",
    "I'm very happy with the results",
    "The app crashes frequently and is frustrating"
]
results = sentiment_pipeline(texts)
for text, result in zip(texts, results):
    print(f"Text: {text}")
    print(f"Sentiment: {result['label']}, Confidence: {result['score']:.2f}")
    print("-" * 50)